config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update]

  resources :users do
    member do
      get :followings, :followers
    end
  end


post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す


get "search" => "search#search"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
  

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  
  
# ユーザーをフォローする
def follow(user_id)
  follower.create(followed_id: user_id)
end

# ユーザーのフォローを外す
def unfollow(user_id)
  follower.find_by(followed_id: user_id).destroy
end

# フォローしていればtrueを返す
def following?(user)
  following_user.include?(user)
end


# 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  

  attachment :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
	before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :postal_code, :prefecture_code, :city, :street])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
  end


  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:edit,:update]

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def edit
     @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

 def create
   current_user.follow(params[:id])
   redirect_to request.referer
 end

 def destroy
   current_user.unfollow(params[:id])
   redirect_to request.referer
 end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def search
    @range = params[:range]
    @word = params[:word]

    if @range == "User"
      @users = User.looks(params[:search], @word )
    else
      @books = Book.looks(params[:search], @word )
    end
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit,:update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end
  
  def followings
    @user  = User.find(params[:id])
    @followings = @user.following_user
  end

  def followers
    @user  = User.find(params[:id])
    @followers = @user.follower_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_book_comments.html.erb
          <table>
           <tr>
           <% book.book_comments.each do |book_comment| %>
             <td>
               <%= link_to user_path(book_comment.user.id) do %>
               <p><%= attachment_image_tag book_comment.user, :profile_image, :fill, 90, 100, fallback: "no_image.jpg" %></p>
                  <%= book_comment.user.name %>
               <% end %>
             </td>
             <td><%= book_comment.comment %></td>
             <td>
               <% if book_comment.user == current_user %>
                <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), class: 'btn-sm btn-danger', method: :delete, remote: true %>
               <% end %>
             </td>
           </tr>
           <% end %>
          </table>

app/views/book_comments/_book_comments_count.html.erb
コメント数：<%= book.book_comments.count %>

app/views/book_comments/_book_comments_form.html.erb
          <%= form_with(model:[book, book_comment], remote: true) do |f| %>
           <%= f.text_area :comment, size:"90x5" %><br>
           <%= f.submit "送信" %>
          <% end %>

app/views/book_comments/create.js.erb
$("#book_comments_count").html("<%= j(render 'book_comments/book_comments_count', book: @book) %>");
$("#book_comments_form").html("<%= j(render 'book_comments/book_comments_form', book: @book, book_comment: @book_comment) %>");
$("#book_comments").html("<%= j(render 'book_comments/book_comments', book: @book ) %>");
$("textarea").val('')

app/views/book_comments/destroy.js.erb
$("#book_comments_count").html("<%= j(render 'book_comments/book_comments_count', book: @book) %>");
$("#book_comments").html("<%= j(render 'book_comments/book_comments', book: @book ) %>");

app/views/books/_form.html.erb
<%= render 'layouts/book_errors', book: book %>
<h2 class="mt-3">New book</h2>
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book',class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <h2>Books</h2>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td id="favorite_buttons_<%= book.id %>"><%= render "favorites/favorites", book: book %></td>
        <td>コメント数：<%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		    <h1>Editing Book</h1>
  		    <%= render 'layouts/book_errors', book: @book %>
        <%= form_with model:@book, local:true do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class:"form-control book_title" %>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class:"form-control book_body" %>
      </div>
      <div class="form-group">
        <%= f.submit 'Update Book',class:"btn btn-success" %>
        <% end %>
      </div>
  		   <%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		   <%= link_to 'Back', books_path, class: "back" %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'users/info', user: @user %>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>

    <div class='col-md-3'>
      <%= render 'users/info', user: @user %>
      <%= render 'form', book: @book_new %>
    </div>

    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		 <tbody>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td id="favorite_buttons_<%= @book.id %>"><%= render "favorites/favorites", book: @book %></td>
          <td id="book_comments_count"><%= render "book_comments/book_comments_count", book: @book %></td>
          <% if @book.user == current_user %>
          <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
          <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
       </tbody>
      </table>

        
          <div id="book_comments">
           <%= render "book_comments/book_comments", book: @book %>
          </div>
        
          <div id="book_comments_form">
           <%= render "book_comments/book_comments_form", book: @book, book_comment: @book_comment %>
          </div>
    </div>
  </div>
</div>

app/views/favorites/_favorites.html.erb
        <% if book.favorited_by?(current_user) %>
        
          <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
           ♥<%= book.favorites.count %>
          <% end %>
        
        <% else %>
        
          <%= link_to book_favorites_path(book), method: :post, remote: true do %>
           ♡<%= book.favorites.count %>
          <% end %>
    
        <% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorites", book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorites", book: @book) %>");

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/search/search.html.erb
 <div class="container px-5 px-sm-0">
  <div class="row">
   <table class="table table-hover table-inverse">
    <% if @range == "User" %>
      <h2>Users search for"<%= @word %>"</h2>
      <thead>
       <tr>
        <th></th>
        <th>name</th>
        <th>introduction</th>
        <th colspan="3"></th>
       </tr>
      </thead>
      <tbody>
         <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 90, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td><%= user.introduction %></td>
        </tr>
         <% end %>
      </tbody>
    <% else %>
      <h2>Books search for"<%= @word %>"</h2>
      <thead>
       <tr>
        <th></th>
        <th>title</th>
        <th>opinion</th>
        <th colspan="3"></th>
       </tr>
      </thead>
      <tbody>
         <% @books.each do |book| %>
        <tr>
          <td><%= attachment_image_tag book.user, :profile_image, :fill, 90, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
        </tr>
         <% end %>
      </tbody>
    <% end %>
   </table>
  </div>
 </div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <h2>Users</h2>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= "フォロー数: #{user.follower.count}" %></td>
        <td><%= "フォロワー数: #{user.followed.count}" %></td>
        <td>
        <% unless user == current_user %>
          <% if current_user.following?(user) %>
            <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
          <% else %>
            <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
          <% end %>
        <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <h2>User info</h2>
  <tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to "#{user.follower.count}", followings_user_path(user.id) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to "#{user.followed.count}", followers_user_path(user.id) %></th>
  </tr>
</table>

<% unless user == current_user %>
  <% if current_user.following?(user) %>
    <%= link_to 'フォロー外す', unfollow_path(user.id), class: "btn btn-success", method: :POST %>
  <% else %>
    <%= link_to 'フォローする', follow_path(user.id), class: "btn btn-success", method: :POST %>
  <% end %>
<% else %>
<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>
<% end %>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
       <h2>User info</h2>
         <%= form_with model:@user, local:true do |f| %>
         <%= render 'layouts/user_errors', user: @user %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: "form-control name" %>
       </div>
       <div class="form-group">
         <%= f.label :image %>
         <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
       </div>
       <div class="form-group">
         <%= f.label :introduction %>
         <%= f.text_area :introduction, class: "form-control introduction" %>
       </div>
       <div class="form-group">
         <%= f.submit "Update User", class: 'btn btn-secondary' %>
         <% end %>
       </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <h2>Follower Users</h2>
   <% if @user.followed.count == 0 %>
   <table class="table table-hover table-inverse">
       <tr>
         <td>フォローしているユーザーはいません</td>
       </tr>
   </table>
   <% else %>
   <table class="table table-hover table-inverse">
     <thead>
       <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
       </tr>
     </thead>
     <tbody>
     <% @followers.each do |user| %>
       <tr>
         <td><%= attachment_image_tag user, :profile_image, :fill, 90, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
         <td><%= user.name %></td>
         <td><%= "フォロー数: #{user.follower.count}" %></td>
         <td><%= "フォロワー数: #{user.followed.count}" %></td>
         <td><%= link_to "Show", user_path(user.id) %></td>
       </tr>
     <% end %>
   <% end %>
     </tbody>
   </table>
  </div>
</div>

app/views/users/followings.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <h2>Follow Users</h2>
   <% if @user.follower.count == 0 %>
   <table class="table table-hover table-inverse">
       <tr>
         <td>フォローしているユーザーはいません</td>
       </tr>
   </table>
   <% else %>
   <table class="table table-hover table-inverse">
     <thead>
       <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
       </tr>
     </thead>
     <tbody>
     <% @followings.each do |user| %>
       <tr>
         <td><%= attachment_image_tag user, :profile_image, :fill, 90, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
         <td><%= user.name %></td>
         <td><%= "フォロー数: #{user.follower.count}" %></td>
         <td><%= "フォロワー数: #{user.followed.count}" %></td>
         <td><%= link_to "Show", user_path(user.id) %></td>
       </tr>
     <% end %>
   <% end %>
     </tbody>
   </table>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'info', user: @user %>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'info', user: @user %>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>